import type { Metadata } from 'next';
import './globals.css';
import { Navbar } from './layout/navbar';
import { Footer } from '../components/Footer';
import QueryProvider from '../utils/provider/QueryProvider';
import { UserProvider }  from '@/contexts/UserContext';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          <UserProvider>
            <Navbar />
            <main> {children} </main>
          </UserProvider>
        </QueryProvider>
        {/* <Footer /> */}
      </body>
    </html>
  ) ;
 }


